/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#7c2e00",
        "on-surface": "#1a1c1d",
        "outline": "#717786",
        "on-tertiary-fixed": "#351000",
        "surface-tint": "#005bc1",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container-low": "#f3f3f5",
        "background": "#f9f9fb",
        "inverse-primary": "#adc6ff",
        "on-primary-fixed": "#001a41",
        "tertiary": "#9e3d00",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdbcc",
        "outline-variant": "#c1c6d7",
        "on-secondary-fixed": "#001a41",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f0f0f2",
        "on-secondary": "#ffffff",
        "surface-container": "#eeeef0",
        "on-secondary-container": "#2d4c83",
        "tertiary-container": "#c64f00",
        "surface-bright": "#f9f9fb",
        "secondary-container": "#a1befd",
        "on-background": "#1a1c1d",
        "primary-container": "#0070eb",
        "error": "#ba1a1a",
        "secondary-fixed": "#d8e2ff",
        "secondary": "#405e96",
        "surface": "#f9f9fb",
        "tertiary-fixed-dim": "#ffb595",
        "surface-variant": "#e2e2e4",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-fixed-variant": "#004493",
        "on-primary-container": "#fefcff",
        "primary-fixed": "#d8e2ff",
        "surface-container-high": "#e8e8ea",
        "on-surface-variant": "#414755",
        "on-secondary-fixed-variant": "#26467d",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "surface-dim": "#d9dadc",
        "inverse-surface": "#2f3132",
        "surface-container-highest": "#e2e2e4",
        "primary": "#0058bc"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        garet: ['Garet', 'sans-serif'],
      },
      borderRadius: { "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px" },
      keyframes: {
        'scroll-left': {          // ← must match animation definition below
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        }
      },
      animation: {
        'scroll-infinite': 'scroll-left 30s linear infinite',  // ← uses 'scroll-left'
      },
    },
  },
  plugins: [],
}
